// Generated by CoffeeScript 1.4.0
var EtAuth;

EtAuth = (function() {

  function EtAuth() {}

  EtAuth.config = function(opts) {
    var et;
    if (opts == null) {
      opts = {};
    }
    this.enabled = opts.auth !== false;
    if (this.enabled) {
      if (!et) {
        et = require('et');
      }
      this.enabled = et.session !== void 0 && et.session.enabled;
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtAuth;

})();

module.exports = EtAuth;
