// Generated by CoffeeScript 1.4.0
var et;

et = {
  session: require('./session'),
  model: require('./model'),
  auth: require('./auth'),
  route: require('./route'),
  al: function(opts) {
    if (opts == null) {
      opts = {};
    }
    console.log('init et.al()');
    if (opts.app) {
      opts.app.use(function(req, res, next) {
        req._et = et;
        return next();
      });
    }
    et.session.config(opts);
    et.model.config(opts);
    et.auth.config(opts);
    et.route.config(opts);
    et.databases = opts.databases;
    return function(req, res, next) {
      console.warn('UNHANDLED request ', req.path);
      return next();
    };
  }
};

module.exports = et;
