// Generated by CoffeeScript 1.4.0
var Et;

Et = (function() {

  function Et() {
    this.session = require('./session');
    this.model = require('./model');
    this.auth = require('./auth');
    this.route = require('./route');
  }

  Et.prototype.al = function(opts) {
    var et;
    if (opts == null) {
      opts = {};
    }
    console.log('init et.al()');
    this.resource = opts.resource;
    et = this;
    this.first = function(req, res, next) {
      req.et = et;
      return next();
    };
    if (opts.app) {
      opts.app.use(this.first);
    }
    this.last = function(req, res, next) {
      console.warn('UNHANDLED request ', req.path);
      return next();
    };
    this.session.config(this, opts);
    this.model.config(this, opts);
    this.auth.config(this, opts);
    this.route.config(this, opts);
    if (opts.app) {
      return this.last;
    }
    return null;
  };

  return Et;

})();

module.exports = new Et();
