// Generated by CoffeeScript 1.4.0
var EtLogger, bunyan;

bunyan = require('bunyan');

module.exports = EtLogger = (function() {

  function EtLogger() {}

  EtLogger.config = function(et, opts) {
    if (opts == null) {
      opts = {};
    }
    if (!opts.logger) {
      opts.logger = {};
    }
    if (!opts.logger.name) {
      opts.logger.name = opts.name || 'untitled';
    }
    if (!opts.logger.level) {
      console.log("TODO: process.env.LOG_LEVEL");
      opts.logger.level = 'debug';
    }
    if (!opts.logger.serializers) {
      opts.logger.serializers = {
        req: function(req) {
          return {
            method: req.method,
            url: req.url,
            headers: req.headers
          };
        }
      };
    }
    et.log = bunyan.createLogger(opts.logger);
    return function(req, res, next) {
      et.log.debug({
        req: req
      });
      return next();
    };
  };

  return EtLogger;

})();
