// Generated by CoffeeScript 1.4.0
var EtLogger, bunyan;

bunyan = require('bunyan');

module.exports = EtLogger = (function() {

  function EtLogger() {}

  EtLogger.config = function(et, opts) {
    var _base;
    if (opts == null) {
      opts = {};
    }
    opts.logger || (opts.logger = {});
    (_base = opts.logger).serializers || (_base.serializers = {});
    if (!opts.logger.name) {
      opts.logger.name = opts.name || 'untitled';
    }
    if (!opts.logger.level) {
      console.log("TODO: process.env.LOG_LEVEL");
      opts.logger.level = 'debug';
    }
    if (!opts.logger.serializers.req) {
      opts.logger.serializers.req = function(req) {
        return {
          method: req.method,
          url: req.url,
          headers: req.headers
        };
      };
    }
    et.log = bunyan.createLogger(opts.logger);
    return function(req, res, next) {
      et.log.debug({
        req: req
      });
      return next();
    };
  };

  return EtLogger;

})();
