// Generated by CoffeeScript 1.4.0
var EtLogger, bunyan;

bunyan = require('bunyan');

module.exports = EtLogger = (function() {

  function EtLogger() {}

  EtLogger.config = function(et, opts) {
    var _base, _base1, _base2, _base3, _base4;
    if (opts == null) {
      opts = {};
    }
    opts.logger || (opts.logger = {});
    (_base = opts.logger).serializers || (_base.serializers = {});
    (_base1 = opts.logger).name || (_base1.name = opts.name || 'untitled');
    (_base2 = opts.logger).level || (_base2.level = process.env.APP_LOG_LEVEL || 'debug');
    (_base3 = opts.logger.serializers).req || (_base3.req = function(req) {
      return {
        method: req.method,
        url: req.url,
        headers: req.headers
      };
    });
    (_base4 = opts.logger.serializers).opts || (_base4.opts = function(opts) {
      return {
        'app name': opts.name,
        'app version': opts.version
      };
    });
    et.log = bunyan.createLogger(opts.logger);
    return function(req, res, next) {
      et.log.debug({
        req: req
      });
      return next();
    };
  };

  return EtLogger;

})();
