// Generated by CoffeeScript 1.4.0
var EtModel;

EtModel = (function() {

  function EtModel() {}

  EtModel.loadModel = function(plural, defn) {
    this.models[plural] = defn;
    if (defn.get instanceof Function) {
      if (defn.get.length === 1) {
        return this.routes.get[plural] = {
          route: "/" + plural + "/:id",
          callback: defn.get
        };
      } else {
        return console.error("model for " + plural + " defines get() without id");
      }
    } else {
      return console.warn("model for " + plural + " defines no get()");
    }
  };

  EtModel.loadModels = function(models) {
    var defn, plural, _results;
    _results = [];
    for (plural in models) {
      defn = models[plural];
      _results.push(this.loadModel(plural, defn));
    }
    return _results;
  };

  EtModel.config = function(opts) {
    var _base;
    if (opts == null) {
      opts = {};
    }
    this.models || (this.models = {});
    this.routes || (this.routes = {});
    (_base = this.routes).get || (_base.get = {});
    if (opts.models) {
      this.loadModels(opts.models);
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtModel;

})();

module.exports = EtModel;
