// Generated by CoffeeScript 1.4.0
var EtRoute;

EtRoute = (function() {

  function EtRoute() {}

  EtRoute.declareRoutes = function(et, opts) {
    var route, _results,
      _this = this;
    _results = [];
    for (route in this.routes.get) {
      console.log("assigning route GET " + this.routes.get[route].route);
      _results.push(opts.app.get(this.routes.get[route].route, function(req, res) {
        var error;
        if (_this.routes.get[route].callback.length !== 2) {
          error = "ROUTE " + route + " requires " + route + ".get(req, res)";
          console.error(error);
          return res.send(500);
        }
        return _this.routes.get[route].callback(req, res);
      }));
    }
    return _results;
  };

  EtRoute.config = function(opts) {
    var et;
    if (opts == null) {
      opts = {};
    }
    if (!et) {
      et = require('et');
    }
    if (!et.model.models) {
      et.model.config(opts);
    }
    this.routes = et.model.routes;
    if (opts.app) {
      this.declareRoutes(et, opts);
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtRoute;

})();

module.exports = EtRoute;
