// Generated by CoffeeScript 1.4.0
var EtRoute;

EtRoute = (function() {

  function EtRoute() {}

  EtRoute.declareRoutes = function(et, opts) {
    var callback, path, route, routes, _results;
    routes = et.model.routes;
    _results = [];
    for (route in routes.get) {
      path = routes.get[route].route;
      callback = routes.get[route].callback;
      if (callback.length !== 2) {
        console.error("ROUTE " + path + " requires " + route + ".get(req, res)");
        continue;
      }
      console.log("assigning route GET " + path);
      _results.push(opts.app.get(path, callback));
    }
    return _results;
  };

  EtRoute.config = function(et, opts) {
    if (opts == null) {
      opts = {};
    }
    if (opts.app) {
      this.declareRoutes(et, opts);
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtRoute;

})();

module.exports = EtRoute;
