// Generated by CoffeeScript 1.4.0
var et;

if (!et) {
  et = {};
}

et.Session = (function() {

  function Session() {}

  Session.loadSession = function(session) {
    if (!session.secret) {
      console.error("session requires secret:'secret'");
      return;
    }
    this.secret = session.secret;
    return this.enabled = true;
  };

  Session.config = function(opts) {
    if (opts == null) {
      opts = {};
    }
    this.enabled = false;
    if (opts.session) {
      this.loadSession(opts.session);
    }
    return function(req, res, next) {
      return next();
    };
  };

  return Session;

})();

module.exports = et.Session;
