// Generated by CoffeeScript 1.4.0
var Connect, ConnectRedis, EtSession, Redis;

Connect = require('connect');

Redis = require('redis');

ConnectRedis = require('connect-redis')(Connect);

EtSession = (function() {

  function EtSession() {}

  EtSession.loadSession = function(opts) {
    var redis;
    console.log("enabling sessions, redis");
    redis = Redis.createClient();
    opts.app.use(Connect.cookieParser());
    return opts.app.use(Connect.session({
      secret: this.secret,
      store: new ConnectRedis({
        client: redis
      })
    }));
  };

  EtSession.config = function(opts) {
    if (opts == null) {
      opts = {};
    }
    this.enabled = opts.session !== false;
    if (this.enabled) {
      if (!(opts.session && opts.session)) {
        console.log("default session secret:'secret'");
        opts.session || (opts.session = {
          secret: 'secret'
        });
      }
      this.secret = opts.session.secret;
      if (opts.app) {
        this.loadSession(opts);
      }
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtSession;

})();

module.exports = EtSession;
