// Generated by CoffeeScript 1.4.0
var Connect, ConnectRedis, EtSession, Redis, et;

Connect = require('connect');

Redis = require('redis');

ConnectRedis = require('connect-redis')(Connect);

if (!et) {
  et = {};
}

EtSession = (function() {

  function EtSession() {}

  EtSession.loadSession = function(session) {
    if (!session.secret) {
      console.error("session requires secret:'secret'");
      return;
    }
    console.log("enabling sessions");
    this.secret = session.secret;
    return this.enabled = true;
  };

  EtSession.config = function(opts) {
    var redis;
    if (opts == null) {
      opts = {};
    }
    this.enabled = false;
    this.store = {};
    if (opts.session) {
      this.loadSession(opts.session);
    }
    if (this.enabled && opts.app) {
      console.log("init redis");
      redis = Redis.createClient();
      opts.app.use(Connect.cookieParser());
      opts.app.use(Connect.session({
        secret: this.secret,
        store: new ConnectRedis({
          client: redis
        })
      }));
    }
    return function(req, res, next) {
      return next();
    };
  };

  return EtSession;

})();

module.exports = EtSession;
