// Generated by CoffeeScript 1.4.0
var EtStatic, fs, nstatic;

nstatic = require('node-static');

fs = require('fs');

module.exports = EtStatic = (function() {

  function EtStatic() {}

  EtStatic.config = function(et, opts) {
    var server;
    if (opts.root && fs.existsSync(opts.root + '/public')) {
      server = new nstatic.Server(opts.root + '/public');
      return opts.app.get(/\/.*/, function(req, res, next) {
        return server.serve(req, res, next);
      });
    }
  };

  return EtStatic;

})();
